# Generated by Django 5.1.5 on 2025-02-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rut',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
