# Generated by Django 5.1.5 on 2025-03-22 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_rut'),
        ('management', '0010_environmentalplan_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='body',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='body_users', to='management.body'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
