# Generated by Django 5.1.5 on 2025-03-22 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_body_alter_customuser_is_active'),
        ('management', '0010_environmentalplan_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_users', to='management.body'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
