# Generated by Django 5.1.5 on 2025-02-04 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_measure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='environmentalplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MeasureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_value', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_measure_reports', to=settings.AUTH_USER_MODEL)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_reports', to='management.measure')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measure_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_measure_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_files', to=settings.AUTH_USER_MODEL)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='management.measurereport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_report_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
