# Generated by Django 5.1.5 on 2025-02-04 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_environmentalplan_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurereport',
            old_name='measure',
            new_name='measure_id',
        ),
    ]
