# Generated by Django 5.1.5 on 2025-02-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_rename_measure_measurereport_measure_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurereport',
            name='reporter',
        ),
    ]
