# Generated by Django 5.1.5 on 2025-02-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_measurereport_reporter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurereport',
            old_name='measure_id',
            new_name='measure',
        ),
        migrations.RenameField(
            model_name='reportfile',
            old_name='report_id',
            new_name='report',
        ),
    ]
