# Generated by Django 5.1.5 on 2025-02-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_body'),
        ('management', '0006_rename_measure_id_measurereport_measure_and_more'),
    ]

    operations = [
    ]
