# Generated by Django 5.1.5 on 2025-02-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_merge_20250205_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reporter', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('fk_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_bodymeasure', to='management.body')),
                ('fk_measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_bodymeasure', to='management.measure')),
            ],
        ),
    ]
