# Generated by Django 5.1.5 on 2025-03-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_bodymeasure_created_at_bodymeasure_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalplan',
            name='short_name',
            field=models.CharField(default='PPDA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bodymeasure',
            name='is_reporter',
            field=models.BooleanField(default=True),
        ),
    ]
