# Generated by Django 5.1.5 on 2025-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_environmentalplan_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='measure_type',
            field=models.CharField(blank=True, choices=[('R', 'Regulación'), ('FAE', 'Fomento de actividades económicas'), ('BIG', 'Beneficios interés general'), ('E', 'Estudios'), ('ED', 'Educación y difusión'), ('PP', 'Política pública')], default=None, max_length=4),
        ),
    ]
