# Generated by Django 5.1.5 on 2025-04-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_measure_measure_type'),
        ('management', '0011_measure_value_type'),
    ]

    operations = [
    ]
