# Generated by Django 5.1.5 on 2025-04-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_progressreportdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='data_created',
            field=models.BooleanField(default=False),
        ),
    ]
