name: Django CI

on:
  pull_request:
    branches: [main, dev]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Read Python version from .python-version file
        id: pyversion
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.pyversion.outputs.PYTHON_VERSION }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Create .env file for CI
        run: |
          echo "SECRET_KEY=temporal-secret-key-ci" >> .env.ci
          echo "DATABASE_URL=sqlite:///db.sqlite3" >> .env.ci
          echo "DEBUG=True" >> .env.ci
          echo "ENV_FILE=.env.ci" >> $GITHUB_ENV
      - name: Check defined env variables
        run: cat .env.ci
      - name: Check for missing migrations
        run: |
          cd sistema_reportes_ppda
          python manage.py makemigrations --check --dry-run
      - name: Run tests
        run: |
          cd sistema_reportes_ppda
          python manage.py test